import Core from './Core';
import { Theme, Icon, useThemeMode, ModeSwitch } from './cartridges/Theme';
import {
  Advert,
  RenderMarkdown,
  Header,
  Footer,
  Nav,
  NavItem,
  PageBreadcrumb,
  MightyButton,
  Search,
  SideAds,
  ThumbMenu,
  ShareMenu,
  IncludeAll,
  LoadingOverlay,
  FieldUpload,
  IndexNav,
  ArrowMenu,
  Siblings,
  Children,
  GoogleMap,
  FlickrAlbum,
  YouTube,
} from './components';
import {
  useLoading,
  useConfig,
  useIsMobile,
  useVersion,
  useFeedback,
  useSiblings,
} from './hooks';
import {
  Uberedux,
  UbereduxProvider,
  useSlice,
  useDispatch,
  useKey,
  setUbereduxKey,
  useVersionCheck,
  resetUberedux,
} from './cartridges/Uberedux';
import { normalizeError } from './lib';
import {
  switchTheme,
  navigateTo,
  routeTo,
  toggleFeedback,
  toggleLoading,
  toggleHideImage,
  uploadToStorage,
  resend,
  reset,
} from './actions';

export { Core };
export {
  switchTheme,
  navigateTo,
  routeTo,
  toggleFeedback,
  toggleLoading,
  uploadToStorage,
  toggleHideImage,
  resend,
  reset,
};
export {
  Advert,
  GoogleMap,
  FlickrAlbum,
  YouTube,
  Header,
  Footer,
  RenderMarkdown,
  Theme,
  Icon,
  ModeSwitch,
  Nav,
  IndexNav,
  Siblings,
  NavItem,
  PageBreadcrumb,
  MightyButton,
  Search,
  SideAds,
  ThumbMenu,
  ShareMenu,
  IncludeAll,
  LoadingOverlay,
  FieldUpload,
  ArrowMenu,
  Children,
};
export { Uberedux, UbereduxProvider, setUbereduxKey, resetUberedux };
export {
  useConfig,
  useIsMobile,
  useFeedback,
  useVersion,
  useSlice,
  useDispatch,
  useKey,
  useLoading,
  useVersionCheck,
  useThemeMode,
  useSiblings,
};
export { normalizeError };
